<?php

namespace Application\Models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-10 at 08:43:35.
 */
class CardTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Card
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Card;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Application\Models\Card::setType
     * @todo   Implement testSetType().
     */
    public function testSetType() {
        $this->object->setType(new \Application\Types\Card(0));
    }

    /**
     * @covers Application\Models\Card::getType
     * @todo   Implement testGetType().
     */
    public function testGetType() {
        $this->object->setType(new \Application\Types\Card(0));
        $this->assertEquals("Two", $this->object->getType()->__toString());
        $this->object->setType(new \Application\Types\Card(12));
        $this->assertEquals("Ace", $this->object->getType()->__toString());
    }

    /**
     * @covers Application\Models\Card::setSuit
     * @todo   Implement testSetSuit().
     */
    public function testSetSuit() {
        $this->object->setSuit(new \Application\Types\Suit(0));
    }

    /**
     * @covers Application\Models\Card::getSuit
     * @todo   Implement testGetSuit().
     */
    public function testGetSuit() {
        $this->object->setSuit(new \Application\Types\Suit(0));
        $this->assertEquals("Hearts", $this->object->getSuit()->__toString());
    }

    /**
     * @covers Application\Models\Card::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        $this->object->setType(new \Application\Types\Card(12));
        $this->object->setSuit(new \Application\Types\Suit(0));
        
        $this->assertEquals("Ace of Hearts", $this->object->__toString());
    }

}
