<?php

namespace Application\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-10 at 17:50:24.
 */
class LogTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Log
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        ;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Application\Controller\Log::log
     * @todo   Implement testLog().
     */
    public function testLog() {
        Log::log('Testing');
    }

    /**
     * @covers Application\Controller\Log::outputLog
     * @todo   Implement testOutputLog().
     */
    public function testOutputLog() {
        $path = __DIR__ . '/tempfile.txt';
        Log::outputLog($path);
        
        $this->assertFileExists($path);
    }
    
    public function testLogsOutput() {
        $path = __DIR__ . '/tempfile1.txt';
        
        Log::clearLog();
        
        Log::log('Testing');
        Log::log('Testing');
        Log::outputLog($path);
        
        $this->assertFileExists($path);
        $contents = "Testing\nTesting";
        
        $file = file_get_contents($path);
        $this->assertEquals($contents, $file);
    }

}
